name: config package

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - id: 'auth'
              uses: 'google-github-actions/auth@v1'
              with:
                service_account:  '${{secrets.SERVICE_ACCOUNT}}'
                token_format: 'access_token'
                workload_identity_provider: ${{secrets.GCP_WORKLOAD_ID}}
            
            - uses: 'docker/login-action@v1'
              with:
                registry: '${{secrets.GCP_ARTIFACT_REGISTRY}}' # or REGION-docker.pkg.dev
                username: 'oauth2accesstoken'
                password: '${{ steps.auth.outputs.access_token }}'              
            
            - name: Set up go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20.5'

            - name: Build
              run: go build -v ./...
            
            - name: Test 
              run: go test -v ./...
